### ISSUE TITLE
jasig/phpcas is abandoned

### ISSUE THREAD

**Issue by CorentinS6** [l3-team/CasGuardBundle#5]
Salut,
J'ai ce message depuis quelques temps :
```
# composer update
Package jasig/phpcas is abandoned, you should avoid using it. Use apereo/phpcas instead.
[...]
# composer why jasig/phpcas
l3/cas-guard-bundle  1.1.15  requires  jasig/phpcas (1.3.8)  
```
L'usage d'apereo/phpcas est-il envisageable à la place de jasig/phpcas ?

Bonne journée,

Corentin

**Comment by mhetru** [comment]
Bonjour Corentin,
oui je viens de m'en rendre compte en créant l'extension d'authentification cas de mediawiki et j'ai utilisé le paquet composer apereo/phpcas dans ce dernier
en effet dans le bundle symfony l3/cas-bundle et aussi l'autre bundle l3/cas-guard-bundle on obtient un warning disant que le paquet composer jasig/phpcas est abandonné et qu'il faut plutôt utiliser apereo/phpcas
je ferai prochainement le changement
amha c'est juste un changement de nom à opérer dans le composer.json mais je revaliderai le tout et retestant tout pour être certain qu'il n'y a pas d'effet(s) de bord
Bon été
a+
Mathieu

**Comment by mhetru** [comment]
c'est fait
a+
Mathieu
